### ISSUE TITLE
Installation via pip fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hrbrmstr/pyhyphen#10]
```
What steps will reproduce the problem?
1. pip install pyhyphen

I'm using MacOS X 10.7 (64bit) with a python 2.6 virtualenv, in case this 
matters.

The installation fails because of whitespace in `setup.py`:


$ pip install pyhyphen
Downloading/unpacking pyhyphen
  Running setup.py egg_info for package pyhyphen
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/Users/diederik/Sites/virtualenvs/allerhande-ah/build/pyhyphen/setup.py", line 143

    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/Users/diederik/Sites/virtualenvs/allerhande-ah/build/pyhyphen/setup.py", line 143



SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /Users/diederik/.pip/pip.log


When I fix the whitespace, and run the install again, I get the following error:


Copying PyHyphen.egg-info to 
/Users/diederik/Sites/virtualenvs/allerhande-ah/lib/python2.6/site-packages/PyHy
phen-1.0beta1-py2.6.egg-info

running install_scripts

writing list of installed files to 
'/var/folders/24/5y_gshzd7vg9f5mv_hpxf1y40000gn/T/pip-7V2UaF-record/install-reco
rd.txt'

Adjusting /.../hyphen/config.py... Done.

Installing dictionary info... Done.

Installing dictionaries... en_US Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/Users/diederik/Sites/virtualenvs/allerhande-ah/build/pyhyphen/setup.py", line 123, in <module>

    install('en_US')

  File "/Users/diederik/Sites/virtualenvs/allerhande-ah/lib/python2.6/site-packages/hyphen/dictools.py", line 48, in install

    s = urllib2.urlopen(url).read()

  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 126, in urlopen

    return _opener.open(url, data, timeout)

  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 391, in open

    response = self._open(req, data)

  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 409, in _open

    '_open', req)

  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 369, in _call_chain

    result = func(*args)

  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 1181, in http_open

    return self.do_open(httplib.HTTPConnection, req)

  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 1156, in do_open

    raise URLError(err)

urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or 
not known>

```

Original issue reported on code.google.com by `vdb...@edoburu-it.nl` on 27 Mar 2012 at 9:40

**Comment by GoogleCodeExporter** [comment]
```
I fear I cannot reproduce the bug. The new setup.py in v2.0b1 does not contain 
white space anymore. The urlopen error should be fixed as v2.0b1 accesses the 
new LibreOffice repo. Let me know if you still encounter problems on your 
platform.  
```

Original comment by `fhaxbox66@googlemail.com` on 1 Aug 2012 at 8:09
- Changed state: **closed**

**Comment by GoogleCodeExporter** [comment]
```
I've tried this out, are you sure about this? :-/


$ pip install pyhyphenDownloading/unpacking pyhyphen
  Downloading PyHyphen-2.0b1.zip (100Kb): 100Kb downloaded
  Running setup.py egg_info for package pyhyphen
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/Users/diederik/Sites/virtualenvs/allerhande-ah/build/pyhyphen/setup.py", line 158

    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/Users/diederik/Sites/virtualenvs/allerhande-ah/build/pyhyphen/setup.py", line 158



SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /Users/diederik/.pip/pip.log

```

Original comment by `vdb...@gmail.com` on 1 Aug 2012 at 10:01

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
When I correct the spacing, the installation fails at a Python 2.7 set syntax:


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/diederik/Sites/virtualenvs/allerhande-ah/build/pyhyphen/setup.py", line 135, in <module>
    from hyphen.dictools import install
  File "/Users/diederik/Sites/virtualenvs/allerhande-ah/lib/python2.6/site-packages/hyphen/__init__.py", line 41, in <module>
    from hyphen import hnj, config
  File "/Users/diederik/Sites/virtualenvs/allerhande-ah/lib/python2.6/site-packages/hyphen/config.py", line 16
    languages = {'af_ZA', 'an_ES', 'ar', 'be_BY', 'bg_BG',

```

Original comment by `vdb...@gmail.com` on 1 Aug 2012 at 10:04
