### ISSUE TITLE
can't install dictionaries

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hrbrmstr/pyhyphen#12]
```
What steps will reproduce the problem?
1. Install pyhypen with python 2.7
2. from hyphen.dictools import install
3. install('en_US')

What is the expected output? What do you see instead?

I hope to install the dictionary, but I have the following error message

<ipython-input-3-3f9c4d992f7e> in <module>()
----> 1 install('en_US')

/usr/local/lib/python2.7/dist-packages/PyHyphen-2.0.2-py2.7-linux-i686.egg/hyphe
n/dictools.pyc in install(language, directory, repos, use_description)
     68 
     69         try:
---> 70             descr_file = urlopen(descr_url)
     71         except URLError:
     72             # OK. So try with the country code.

/usr/lib/python2.7/urllib2.pyc in urlopen(url, data, timeout)
    125     if _opener is None:
    126         _opener = build_opener()
--> 127     return _opener.open(url, data, timeout)
    128 
    129 def install_opener(opener):

/usr/lib/python2.7/urllib2.pyc in open(self, fullurl, data, timeout)
    391 
    392         req.timeout = timeout
--> 393         protocol = req.get_type()
    394 
    395         # pre-process request

/usr/lib/python2.7/urllib2.pyc in get_type(self)
    253             self.type, self.__r_type = splittype(self.__original)
    254             if self.type is None:
--> 255                 raise ValueError, "unknown url type: %s" % 
self.__original
    256         return self.type
    257 

ValueError: unknown url type: $repoen_US/dictionaries.xcu



What version of the product are you using? On what operating system?

Last pyhyphen form pypi (2.02)

Please provide any additional information below.


```

Original issue reported on code.google.com by `zunbe...@gmail.com` on 9 Jan 2013 at 11:58

**Comment by GoogleCodeExporter** [comment]
```
The latest releases should have tackled this.
```

Original comment by `fhaxbox66@googlemail.com` on 2 Nov 2014 at 8:45
- Changed state: **closed**

**Comment by frankwxu** [comment]
I have the similar problem.

Code;

from hyphen import Hyphenator, dict_info
from hyphen.dictools import *

for lang in ['en_US']:
    if not is_installed(lang): install(lang)

Error:

Traceback (most recent call last):
  File "C:\Users\frank-tablet\Dropbox\projects\pythonProject\hello\test.py", line 11, in <module>
    if not is_installed(lang): install(lang)
  File "C:\python351\lib\site-packages\hyphen\dictools.py", line 71, in install
    descr_file = urlopen(descr_url)
  File "C:\python351\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "C:\python351\lib\urllib\request.py", line 450, in open
    req = Request(fullurl, data)
  File "C:\python351\lib\urllib\request.py", line 268, in **init**
    self.full_url = url
  File "C:\python351\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\python351\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '$repoen_US/dictionaries.xcu'

Window 7,
Python: 3.51
