### ISSUE TITLE
hyphen_config.py assumes setup.py installed into sys.path

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hrbrmstr/pyhyphen#2]
```
I'm trying to create a Debian package of this project.  With version
0.8, it fails to install.  I believe the problem is that "setup.py
install" invokes hyphen_config.py -- which assumes hyphen is in the
default Python sys.path.  This is not the case when preparing
packages.  Below is a partial transcript demonstrating the problem.

   dh_auto_install
running install
running build
running build_py
running build_ext
running install_lib
creating /home/twb/VCS/PyHyphen-0.8/debian/python-pyhyphen/usr
creating /home/twb/VCS/PyHyphen-0.8/debian/python-pyhyphen/usr/lib
creating /home/twb/VCS/PyHyphen-0.8/debian/python-pyhyphen/usr/lib/python2.5
creating 
/home/twb/VCS/PyHyphen-0.8/debian/python-pyhyphen/usr/lib/python2.5/site-package
s
creating 
/home/twb/VCS/PyHyphen-0.8/debian/python-pyhyphen/usr/lib/python2.5/site-package
s/hyphen
copying build/lib.linux-i686-2.5/hyphen/hyph_en_US.dic -> 
/home/twb/VCS/PyHyphen-0.8/debian/python-pyhyphen/usr/lib/python2.5/site-package
s/hyphen
copying build/lib.linux-i686-2.5/hyphen/__init__.py -> 
/home/twb/VCS/PyHyphen-0.8/debian/python-pyhyphen/usr/lib/python2.5/site-package
s/hyphen
copying build/lib.linux-i686-2.5/hyphen/dictools.py -> 
/home/twb/VCS/PyHyphen-0.8/debian/python-pyhyphen/usr/lib/python2.5/site-package
s/hyphen
copying build/lib.linux-i686-2.5/hyphen/config.py -> 
/home/twb/VCS/PyHyphen-0.8/debian/python-pyhyphen/usr/lib/python2.5/site-package
s/hyphen
copying build/lib.linux-i686-2.5/hyphen/hnj.so -> 
/home/twb/VCS/PyHyphen-0.8/debian/python-pyhyphen/usr/lib/python2.5/site-package
s/hyphen
copying build/lib.linux-i686-2.5/textwrap2.py -> 
/home/twb/VCS/PyHyphen-0.8/debian/python-pyhyphen/usr/lib/python2.5/site-package
s
running install_egg_info
Writing 
/home/twb/VCS/PyHyphen-0.8/debian/python-pyhyphen/usr/lib/python2.5/site-package
s/PyHyphen-0.8.egg-info
Configuring...
Traceback (most recent call last):
  File "setup.py", line 118, in <module>
    if 'install' in sys.argv: execfile('hyphen_config.py')
  File "hyphen_config.py", line 22, in <module>
    cfg()
  File "hyphen_config.py", line 7, in cfg
    import hyphen
ImportError: No module named hyphen
dh_auto_install: command returned error code 256
make: *** [binary] Error 1
dpkg-buildpackage: failure: fakeroot debian/rules binary gave error exit status 
2
debuild: fatal error at line 1319:
dpkg-buildpackage -rfakeroot -D -us -uc failed

```

Original issue reported on code.google.com by `trentb...@gmail.com` on 2 Oct 2008 at 6:53

**Comment by GoogleCodeExporter** [comment]
Original comment by `fhaxbox66@googlemail.com` on 13 Oct 2008 at 1:50
- Changed state: **Closed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `trentb...@gmail.com` on 22 Nov 2008 at 2:57
