### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u03b4' in position 0: ordinal not in range(256)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hrbrmstr/pyhyphen#4]
```
From this transcript, you can see that rst2pdf crashes when trying to
make a PDF containing the Greek letter "delta" if and only if pyhyphen
is installed.

$ rst2pdf Requirements.txt 
Traceback (most recent call last):
  File "/usr/bin/rst2pdf", line 8, in <module>
    load_entry_point('rst2pdf==0.9dev-r412', 'console_scripts', 'rst2pdf')()
  File "/var/lib/python-support/python2.5/rst2pdf/createpdf.py", line 1229, in main
    compressed=options.compressed)
  File "/var/lib/python-support/python2.5/rst2pdf/createpdf.py", line 1001, in createPdf
    pdfdoc.build(elements)
  File "/var/lib/python-support/python2.5/reportlab/platypus/doctemplate.py", line 756, in build
    self.handle_flowable(flowables)
  File "/var/lib/python-support/python2.5/reportlab/platypus/doctemplate.py", line 649, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
  File "/var/lib/python-support/python2.5/reportlab/platypus/frames.py", line 159, in _add
    w, h = flowable.wrap(aW, h)
  File "/var/lib/python-support/python2.5/reportlab/platypus/flowables.py", line 520, in wrap
    W,H = _listWrapOn(self._content,aW,self.canv,dims=dims)
  File "/var/lib/python-support/python2.5/reportlab/platypus/flowables.py", line 464, in _listWrapOn
    w,h = f.wrapOn(canv,availWidth,0xfffffff)
  File "/var/lib/python-support/python2.5/reportlab/platypus/flowables.py", line 113, in wrapOn
    w, h = self.wrap(aW,aH)
  File "/var/lib/python-support/python2.5/reportlab/platypus/paragraph.py", line 800, in wrap
    blPara = self.breakLines([first_line_width, later_widths])
  File "/var/lib/python-support/python2.5/wordaxe/rl/paragraph.py", line 808, in breakLines
    hyphWord = hyphenator.hyphenate(uniwordstr)
  File "/var/lib/python-support/python2.5/wordaxe/hyphen.py", line 315, in hyphenate
    hword = self.i_hyphenate(aWord)
  File "/var/lib/python-support/python2.5/wordaxe/plugins/PyHyphenHyphenator.py", line 105, in i_hyphenate
    return ExplicitHyphenator.i_hyphenate_derived(self, aWord)
  File "/var/lib/python-support/python2.5/wordaxe/ExplicitHyphenator.py", line 136, in i_hyphenate_derived
    hword = self.stripper.apply_stripped(word, self.hyph)
  File "/var/lib/python-support/python2.5/wordaxe/BaseHyphenator.py", line 60, in apply_stripped
    result = func(base, *args, **kwargs)
  File "/var/lib/python-support/python2.5/wordaxe/plugins/PyHyphenHyphenator.py", line 98, in hyph
    hword = HyphenatedWord(aWord, hyphenations=self.zerlegeWort(aWord))
  File "/var/lib/python-support/python2.5/wordaxe/plugins/PyHyphenHyphenator.py", line 62, in zerlegeWort
    for left, right in self.hnj.pairs(zusgWort):
  File "/var/lib/python-support/python2.5/hyphen/__init__.py", line 199, in pairs
    return self.__hyphenate__.apply(word, mode)
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u03b4' in 
position 0: ordinal not in range(256)
$ dpkg -l rst2pdf python-{reportlab,hyphen,wordaxe}
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Cfg-files/Unpacked/Failed-cfg/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Hold/Reinst-required/X=both-problems (Status,Err: uppercase=bad)
||/ Name                        Version                     Description
+++-===========================-===========================-====================
==================================================
ii  python-hyphen               0.8-1                       Python wrapper for 
libhnj (libhyphen)
ii  python-reportlab            2.2-2                       ReportLab library 
to create PDF documents using Python
ii  python-wordaxe              0.2.6-1                     germanic (and 
basic) hyphenation algorithms
ii  rst2pdf                     0.9+svn412-1                ReportLab-based 
reStructuredText to PDF renderer
$ locale
LANG=en_AU.utf8
LC_CTYPE="en_AU.utf8"
LC_NUMERIC="en_AU.utf8"
LC_TIME="en_AU.utf8"
LC_COLLATE=C
LC_MONETARY="en_AU.utf8"
LC_MESSAGES="en_AU.utf8"
LC_PAPER="en_AU.utf8"
LC_NAME="en_AU.utf8"
LC_ADDRESS="en_AU.utf8"
LC_TELEPHONE="en_AU.utf8"
LC_MEASUREMENT="en_AU.utf8"
LC_IDENTIFICATION="en_AU.utf8"
LC_ALL=
$ sudo aptitude purge python-hyphen
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Reading extended state information       
Initializing package states... Done
The following packages will be REMOVED:
  python-hyphen{p} 
0 packages upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
Need to get 0B of archives. After unpacking 193kB will be freed.
Do you want to continue? [Y/n/?] 
Writing extended state information... Done
(Reading database ... 37977 files and directories currently installed.)
Removing python-hyphen ...
Processing triggers for python-support ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Reading extended state information      
Initializing package states... Done

Current status: 1024 new [-1].
$ rst2pdf Requirements.txt 
[WARNING] createpdf.py L115 Can't load PyHyphen hyphenator for language en_US, 
trying PyHnj hyphenator
WARNING:rst2pdf:Can't load PyHyphen hyphenator for language en_US, trying PyHnj 
hyphenator
[WARNING] flowables.py L293 BoundByWidth too wide to fit in frame: 
<BoundByWidth at 0x97b6d8c> size= maxWidth=238.015748031x
WARNING:rst2pdf:BoundByWidth too wide to fit in frame: <BoundByWidth at 
0x97b6d8c> size= maxWidth=238.015748031x
[WARNING] flowables.py L293 BoundByWidth too wide to fit in frame: 
<BoundByWidth at 0x97bb30c> size= maxWidth=238.015748031x
WARNING:rst2pdf:BoundByWidth too wide to fit in frame: <BoundByWidth at 
0x97bb30c> size= maxWidth=238.015748031x
[WARNING] flowables.py L293 BoundByWidth too wide to fit in frame: 
<BoundByWidth at 0x97bb46c> size= maxWidth=238.015748031x
WARNING:rst2pdf:BoundByWidth too wide to fit in frame: <BoundByWidth at 
0x97bb46c> size= maxWidth=238.015748031x

```

Original issue reported on code.google.com by `trentb...@gmail.com` on 8 Oct 2008 at 12:56

**Comment by GoogleCodeExporter** [comment]
```
See also wordaxe bug #2138589 - this seems to be a problem in the pyhyphen 
package.
I am using an older version of pyhpyhen.

It fails for the input string u"raven\u2019s" with the following error:
  File "c:\Python25\Lib\site-packages\hyphen\__init__.py", line 213, in pairs
    return self.hyph.apply(word, mode)
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2019' in position
 5: ordinal not in range(256)

```

Original comment by `h.vonbar...@gmail.com` on 12 Oct 2008 at 8:34

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
Original comment by `fhaxbox66@googlemail.com` on 12 Oct 2008 at 5:39

**Comment by GoogleCodeExporter** [comment]
Original comment by `fhaxbox66@googlemail.com` on 13 Oct 2008 at 1:50
- Changed state: **Closed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `trentb...@gmail.com` on 22 Nov 2008 at 2:51
