### ISSUE TITLE
Charset LookupError for some dictionaries

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hrbrmstr/pyhyphen#6]
```
What steps will reproduce the problem?
>>> from hyphen import dictools, hyphenator
>>> dictools.install("sv_SE")
>>> hyphenator("sv_SE").pairs(u"begravningsentreprenör")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "hyphen/__init__.py", line 175, in pairs
    return self.__hyphenate__.apply(word, mode)
LookupError: unknown encoding: charset ISO8859-1


What is the expected output? What do you see instead?
>>> from hyphen import dictools, hyphenator
>>> dictools.install("sv_SE")
>>> hyphenator("sv_SE").pairs(u"begravningsentreprenör")
[[u'be', u'gravningsentrepren\xf6r'], [u'begrav', u'ningsentrepren\xf6r'], 
[u'begravnings', u'entrepren\xf6r'], [u'begravningsent', u'repren\xf6r'], 
[u'begravningsentre', u'pren\xf6r']]


What version of the product are you using? On what operating system?
0.9.3

Please provide any additional information below.

Issue is caused by some dictionaries having "charset" before the charset on the 
first line of the file.

I have fixed it by making a small change to hyphen.c see attached diff.
```

Original issue reported on code.google.com by `stephen....@gmail.com` on 22 Jun 2010 at 4:39

Attachments:
- [pyhyphen_charset_fix.diff](https://storage.googleapis.com/google-code-attachments/pyhyphen/issue-6/comment-0/pyhyphen_charset_fix.diff)

**Comment by GoogleCodeExporter** [comment]
Original comment by `fhaxbox66@googlemail.com` on 1 Aug 2012 at 7:51
- Changed state: **Closed**
